version: "3"

volumes:
    mongo:
    redis:

services:
    # The app is going to run on the host machine's port 4444 in development
    nginx:
        restart: always
        depends_on:
            - express_api
            # - puzzle_client
            - gatsby
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/nginx
        ports:
            - "4444:80"

    # The main content pages are in this container
    gatsby:
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/gatsby
        volumes:
            - /app/node_modules
            - ./containers/gatsby:/app
        environment:
            - NODE_ENV=development
            - GATSBY_WEBPACK_PUBLICPATH=/
        working_dir: /app
        command: ./containers/gatsby/entrypoint.sh
        ports:
            - "8000:8000"
            # - "9929:9929"
            # - "9230:9230"

    # The API for the puzzle server
    express_api:
        depends_on:
            - mongo
            - redis
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/express_api
        volumes:
            - /app/node_modules
            - ./containers/express_api:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - SESSION_SECRET="this is only for development"

    # The MERN database
    mongo:
        image: mongo
        volumes:
            - mongo:/data/db

    # Express.js sessions
    redis:
        image: "redis:latest"
        volumes:
            - redis:/data

    # React SPA
    # puzzle_client:
    #     build:
    #         dockerfile: Dockerfile.dev
    #         context: ./containers/puzzle_client
    #     depends_on:
    #         - express_api
    #     volumes:
    #         - /app/node_modules
    #         - ./containers/puzzle_client:/app
