version: '3'

volumes:
    mongo:

services:
    web:
        build:
            context: ./express_api
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./express_api:/app
        depends_on:
            - mongo

    mongo:
        image: mongo
        # TODO: don't expose port in production
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db
