version: '3'

volumes:
    mongo:

services:
    nginx:
        restart: always
        depends_on:
            - api
            - mongo
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - "3000:80"

    api:
        build:
            context: ./express_api
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./express_api:/app
        depends_on:
            - mongo

    mongo:
        image: mongo
        # TODO: don't expose port in production
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db
